### PR TITLE
ci: change pipeline buld context

### PR DESCRIPTION
**Pull request by mmpetarpeshev**

### CODE REVIEW

**Comment by kenodressel** [comment]
I guess this uncovered another bug :) The CI should be running here (eg. if we change something on the CI) and if something is changed on contract repo, we need to re-deploy both, the frontend & backends :)

**Comment by kenodressel** [comment]
I've seen the code that currently exists but when we look at the docker file we see a few other dependencies. And when there are changes to the CI, the CI should also run. Otherwise we don't know if it works right?

**Comment by mmpetarpeshev** [comment]
1. About the other dependencies I can't say do we need something to be run . As far as I remember we wanted to run it per folder. If we have a new requirement it can be changed, np here.
2. About the pipelines, really depends on the case, but usually, I'm testing with a test repo. That can be changed too.

**Review by thepiwo — APPROVED** [review]
should be fine

**Pull request merged**
